### ISSUE TITLE
Translation into Russian

### ISSUE THREAD

**Issue by ObKich** [skycatminepokie/mystical#199]
I tried to translate the mod into Russian and I think it can be added to the mod itself. This may not be the most accurate translation, but it will be much more convenient for Russian-speaking people using this mod.
[ru_ru.json](https://github.com/user-attachments/files/17089569/ru_ru.json)

**Comment by skycatminepokie** [comment]
I will take a look and add it. Thank you!

**Comment by skycatminepokie** [comment]
Added in #200 , thanks for helping out!
